# Generated by Django 4.2 on 2023-10-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_id', models.CharField(max_length=255)),
                ('profile_name', models.CharField(max_length=255)),
                ('whatsapp_id', models.CharField(max_length=255)),
                ('from_id', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('phone_number', models.CharField(max_length=255)),
                ('message_text', models.TextField()),
            ],
        ),
    ]
